language: php

php:
    - 7.1
    - nightly

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

script: bin/phpunit

branches:
    only:
        - gh-pages
