gems:
  - jekyll-redirect-from
  - kramdown
name: Keyvan Akbary
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:title/
url: "http://keyvanakbary.com"
description: Tech Lead en TransferWise. Autor del libro “Domain-Driven Design in PHP”.
excerpt_separator: <!--more-->
